In [1]:
import xarray as xr
import numpy as np

In [2]:
data = xr.load_dataset('./download.nc')
data

<xarray.Dataset>
Dimensions:    (latitude: 721, longitude: 1440, time: 24)
Coordinates:
  * longitude  (longitude) float32 0.0 0.25 0.5 0.75 ... 359.0 359.2 359.5 359.8
  * latitude   (latitude) float32 90.0 89.75 89.5 89.25 ... -89.5 -89.75 -90.0
  * time       (time) datetime64[ns] 2000-01-01 ... 2000-01-01T23:00:00
Data variables:
    u100       (time, latitude, longitude) float32 0.3306 0.3306 ... 0.3276
    v100       (time, latitude, longitude) float32 -0.439 -0.439 ... 0.2162
Attributes:
    Conventions:  CF-1.6
    history:      2021-04-13 04:37:10 GMT by grib_to_netcdf-2.16.0: /opt/ecmw...

In [3]:
wind_speed = np.sqrt(data['u100']**2 + data['v100']**2)
wind_speed

<xarray.DataArray (time: 24, latitude: 721, longitude: 1440)>
array([[[ 0.54954606,  0.54954606,  0.54954606, ...,  0.54954606,
          0.54954606,  0.54954606],
        [10.980949  , 10.976104  , 10.970875  , ..., 10.968889  ,
         10.973651  , 10.977718  ],
        [11.157799  , 11.152645  , 11.142836  , ..., 11.142683  ,
         11.15038   , 11.154325  ],
        ...,
        [ 5.9308333 ,  5.933312  ,  5.9325733 , ...,  5.9136033 ,
          5.9188533 ,  5.925132  ],
        [ 5.45025   ,  5.4512877 ,  5.4520454 , ...,  5.437568  ,
          5.442477  ,  5.4463477 ],
        [ 0.30773714,  0.30773714,  0.30773714, ...,  0.30773714,
          0.30773714,  0.30773714]],

       [[ 0.52219653,  0.52219653,  0.52219653, ...,  0.52219653,
          0.52219653,  0.52219653],
        [10.950104  , 10.945359  , 10.940196  , ..., 10.941288  ,
         10.944643  , 10.947579  ],
        [10.875379  , 10.869955  , 10.85993   , ..., 10.866541  ,
         10.871957  , 10.874864  ],
...
        [ 5.0269055 ,  5.030456  ,  5.0320234 , ...,  5.006483  ,
          5.014244  ,  5.020876  ],
        [ 5.068251  ,  5.069969  ,  5.0717177 , ...,  5.0544133 ,
          5.0589075 ,  5.06357   ],
        [ 0.38785225,  0.38785225,  0.38785225, ...,  0.38785225,
          0.38785225,  0.38785225]],

       [[ 1.1948918 ,  1.1948918 ,  1.1948918 , ...,  1.1948918 ,
          1.1948918 ,  1.1948918 ],
        [11.893567  , 11.892845  , 11.892769  , ..., 11.873347  ,
         11.880492  , 11.886868  ],
        [12.786556  , 12.788195  , 12.787565  , ..., 12.757386  ,
         12.769773  , 12.779507  ],
        ...,
        [ 5.2427125 ,  5.245353  ,  5.246754  , ...,  5.2237062 ,
          5.229663  ,  5.2356763 ],
        [ 5.3540645 ,  5.355213  ,  5.357197  , ...,  5.3403125 ,
          5.344894  ,  5.349496  ],
        [ 0.39245716,  0.39245716,  0.39245716, ...,  0.39245716,
          0.39245716,  0.39245716]]], dtype=float32)
Coordinates:
  * longitude  (longitude) float32 0.0 0.25 0.5 0.75 ... 359.0 359.2 359.5 359.8
  * latitude   (latitude) float32 90.0 89.75 89.5 89.25 ... -89.5 -89.75 -90.0
  * time       (time) datetime64[ns] 2000-01-01 ... 2000-01-01T23:00:00

In [4]:
a = 
a

<xarray.DataArray (time: 24)>
array([0.84397054, 0.65142596, 0.6792895 , 0.69869065, 0.69982886,
       0.8038333 , 0.7949004 , 0.70299006, 0.7698889 , 0.9856809 ,
       0.5863243 , 0.98583025, 1.9260961 , 2.649634  , 2.6599052 ,
       2.8123991 , 3.1263456 , 2.8893528 , 2.4065657 , 2.0309222 ,
       1.6975172 , 1.3437201 , 0.7294287 , 0.57949823], dtype=float32)
Coordinates:
    longitude  float32 2.0
    latitude   float32 42.0
  * time       (time) datetime64[ns] 2000-01-01 ... 2000-01-01T23:00:00

In [13]:
lats = [0, 0.25, 0.5]
lngs = [1, 1.25, 1.5, 1.75]
edges = np.histogram(wind_speed.sel(latitude=0, longitude=0), range=(0, 100), bins=1000)[1][:-1]

new_data = np.array([
    np.array([
        np.histogram(wind_speed.sel(latitude=lat, longitude=lng), range=(0, 100), bins=1000)[0]
        for lng in lngs  # wind_speed['longitude'].values
    ])
    for lat in lats # wind_speed['lait'].values
])
new_da = xr.DataArray(new_data, coords=[lats, lngs, edges], dims=["lat", "lng", "edges"])
new_da

<xarray.DataArray (lat: 3, lng: 4, edges: 1000)>
array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]])
Coordinates:
  * lat      (lat) float64 0.0 0.25 0.5
  * lng      (lng) float64 1.0 1.25 1.5 1.75
  * edges    (edges) float32 0.0 0.1 0.2 0.3 0.4 ... 99.5 99.6 99.7 99.8 99.9

In [29]:
def transform_era5_lon_to_wgs84_lon(lon):
    return np.mod(lon + 180, 360) - 180

In [36]:
transform_era5_lon_to_wgs84_lon(359.25)

-0.75